### ISSUE TITLE
Carthage: Dependency "RxIGListKit" has no shared framework schemes

### ISSUE THREAD

**Issue by petersktang** [RxSwiftCommunity/RxIGListKit#1]
Need help:

`github "RxSwiftCommunity/RxIGListKit" ~> 1.0.0
`

after executing "carthage update" with the above, it returns the below
```
*** Skipped building RxIGListKit due to the error:
Dependency "RxIGListKit" has no shared framework schemes
```

Thanks

**Comment by Bruce-pac** [comment]
@petersktang This issue was resolved. you can try `github "RxSwiftCommunity/RxIGListKit" "master"`
