### ISSUE TITLE
No such module 'IGListKit.IGListDiffable'

### ISSUE THREAD

**Issue by berkakkerman** [RxSwiftCommunity/RxIGListKit#5]
After I installed RxIGListKit library with pod. Installing like below:

> 
> Installing IGListDiffKit (4.0.0)
> Installing IGListKit (4.0.0)
> Installing RxIGListKit (1.0.1)

Unfortunately, throws a compile error. like below:

> No such module 'IGListKit.IGListDiffable'

**Which version should be installed ?**

### Environment

- Xcode 11.6 
- Swift 5

**Comment by Bruce-pac** [comment]
please use the latest 2.0.0 version

**Comment by berkakkerman** [comment]
There is no issue anymore. Thank you. :tada:
