### ISSUE TITLE
RxIGListKit doesn't work with RxSwift 5.1.1 version

### ISSUE THREAD

**Issue by RagdeSey** [RxSwiftCommunity/RxIGListKit#6]
Hi, I tried to use RxIGListKit alongside to RxSwift version 5.1.1, because there's an known issue with IGListKit version, I had to configure the pod to 2.0.0v, nevertheless when I tried to install it, It throws the following error:

![Screen Shot 2020-10-14 at 23 51 47](https://user-images.githubusercontent.com/20229858/96082313-3c920900-0e78-11eb-8296-f44e2f6cd9f2.png)

In fact the problem it is the RxSwift version, however this version is mandatory.

Could you help me with issue? Thank you in advance 👐

**Comment by Bruce-pac** [comment]
please use 2.0.1

**Comment by RagdeSey** [comment]
thanks it worked 👍
